#!/bin/bash

# Following environments needs to be set (without the < >)
GH_TOKEN=<your-personal-token-with-access-to-github-repository>
GH_USERNAME=<your-github-username-associated-with-the-token>
GH_REPO=<your-github-repository>
DC_TOKEN=<your-discord-bot-token>
DC_CHANNEL=<your-discord-channel>

# If you wish to debug the bot, add
# APBOT_DEBUG=true